//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apple {
            get {
                object obj = ResourceManager.GetObject("apple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bedrock {
            get {
                object obj = ResourceManager.GetObject("bedrock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coal_ore {
            get {
                object obj = ResourceManager.GetObject("coal_ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobblestone {
            get {
                object obj = ResourceManager.GetObject("cobblestone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_ore {
            get {
                object obj = ResourceManager.GetObject("diamond_ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt {
            get {
                object obj = ResourceManager.GetObject("dirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dragon_egg {
            get {
                object obj = ResourceManager.GetObject("dragon_egg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap end_bricks {
            get {
                object obj = ResourceManager.GetObject("end_bricks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap end_stone {
            get {
                object obj = ResourceManager.GetObject("end_stone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap endframe_side {
            get {
                object obj = ResourceManager.GetObject("endframe_side", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap endframe_top {
            get {
                object obj = ResourceManager.GetObject("endframe_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_ore {
            get {
                object obj = ResourceManager.GetObject("gold_ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass_block {
            get {
                object obj = ResourceManager.GetObject("grass_block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gravel {
            get {
                object obj = ResourceManager.GetObject("gravel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heartIcon {
            get {
                object obj = ResourceManager.GetObject("heartIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heartIcon2 {
            get {
                object obj = ResourceManager.GetObject("heartIcon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iron_ore {
            get {
                object obj = ResourceManager.GetObject("iron_ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lava {
            get {
                object obj = ResourceManager.GetObject("lava", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;661&lt;/x&gt;
        ///		&lt;y&gt;123&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;3&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;711&lt;/x&gt;
        ///		&lt;y&gt;73&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;3&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;761&lt;/x&gt;
        ///		&lt;y&gt;23&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;3&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;511&lt;/x&gt;
        ///		&lt;y&gt;173&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;3&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;461&lt;/x&gt;
        ///		&lt;y&gt;173&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;288&lt;/x&gt;
        ///		&lt;y&gt;121&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;288&lt;/x&gt;
        ///		&lt;y&gt;221&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;288&lt;/x&gt;
        ///		&lt;y&gt;171&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;238&lt;/x&gt;
        ///		&lt;y&gt;121&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;238&lt;/x&gt;
        ///		&lt;y&gt;22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level10 {
            get {
                return ResourceManager.GetString("Level10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;490&lt;/x&gt;
        ///		&lt;y&gt;263&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;14&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;540&lt;/x&gt;
        ///		&lt;y&gt;263&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;14&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;740&lt;/x&gt;
        ///		&lt;y&gt;263&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;13&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;690&lt;/x&gt;
        ///		&lt;y&gt;263&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;13&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;790&lt;/x&gt;
        ///		&lt;y&gt;26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level11 {
            get {
                return ResourceManager.GetString("Level11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;888&lt;/x&gt;
        ///		&lt;y&gt;18&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;838&lt;/x&gt;
        ///		&lt;y&gt;18&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;738&lt;/x&gt;
        ///		&lt;y&gt;18&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;688&lt;/x&gt;
        ///		&lt;y&gt;18&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;88&lt;/x&gt;
        ///		&lt;y&gt;18&lt;/y&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level12 {
            get {
                return ResourceManager.GetString("Level12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;261&lt;/x&gt;
        ///		&lt;y&gt;273&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;19&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;711&lt;/x&gt;
        ///		&lt;y&gt;273&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;19&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;661&lt;/x&gt;
        ///		&lt;y&gt;273&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;19&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;761&lt;/x&gt;
        ///		&lt;y&gt;273&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;5&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;261&lt;/x&gt;
        ///		&lt;y&gt;373 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;511&lt;/x&gt;
        ///		&lt;y&gt;23&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;19&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;111&lt;/x&gt;
        ///		&lt;y&gt;123&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;19&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;661&lt;/x&gt;
        ///		&lt;y&gt;273&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;7&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;61&lt;/x&gt;
        ///		&lt;y&gt;323&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;6&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;111&lt;/x&gt;
        ///		&lt;y&gt;273&lt;/y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;12&lt;/x&gt;
        ///		&lt;y&gt;173&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;5&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;62&lt;/x&gt;
        ///		&lt;y&gt;173&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;5&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;561&lt;/x&gt;
        ///		&lt;y&gt;273&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;5&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;511&lt;/x&gt;
        ///		&lt;y&gt;173&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;8&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;511&lt;/x&gt;
        ///		&lt;y&gt;223&lt;/y&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;211&lt;/x&gt;
        ///		&lt;y&gt;73&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;8&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;211&lt;/x&gt;
        ///		&lt;y&gt;223&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;8&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;211&lt;/x&gt;
        ///		&lt;y&gt;173&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;8&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;61&lt;/x&gt;
        ///		&lt;y&gt;223&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;8&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;61&lt;/x&gt;
        ///		&lt;y&gt;173&lt;/y&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;12&lt;/x&gt;
        ///		&lt;y&gt;93&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;5&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;611&lt;/x&gt;
        ///		&lt;y&gt;93&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;21&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;661&lt;/x&gt;
        ///		&lt;y&gt;143&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;21&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;161&lt;/x&gt;
        ///		&lt;y&gt;143&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;5&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;161&lt;/x&gt;
        ///		&lt;y&gt;93&lt;/y&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level6 {
            get {
                return ResourceManager.GetString("Level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;572&lt;/x&gt;
        ///		&lt;y&gt;140&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;572&lt;/x&gt;
        ///		&lt;y&gt;190&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;572&lt;/x&gt;
        ///		&lt;y&gt;90&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;572&lt;/x&gt;
        ///		&lt;y&gt;40&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;9&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;472&lt;/x&gt;
        ///		&lt;y&gt;190&lt;/y&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level7 {
            get {
                return ResourceManager.GetString("Level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;168&lt;/x&gt;
        ///		&lt;y&gt;155&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;168&lt;/x&gt;
        ///		&lt;y&gt;255&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;168&lt;/x&gt;
        ///		&lt;y&gt;205&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;118&lt;/x&gt;
        ///		&lt;y&gt;155&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;22&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;118&lt;/x&gt;
        ///		&lt;y&gt;25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level8 {
            get {
                return ResourceManager.GetString("Level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;540&lt;/x&gt;
        ///		&lt;y&gt;88&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;10&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;490&lt;/x&gt;
        ///		&lt;y&gt;138&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;10&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;440&lt;/x&gt;
        ///		&lt;y&gt;12&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;10&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;390&lt;/x&gt;
        ///		&lt;y&gt;138&lt;/y&gt;
        ///		&lt;width&gt;50&lt;/width&gt;
        ///		&lt;height&gt;50&lt;/height&gt;
        ///		&lt;id&gt;10&lt;/id&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;340&lt;/x&gt;
        ///		&lt;y&gt;88&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level9 {
            get {
                return ResourceManager.GetString("Level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftBkgd {
            get {
                object obj = ResourceManager.GetObject("minecraftBkgd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftLogo {
            get {
                object obj = ResourceManager.GetObject("minecraftLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nether_portal {
            get {
                object obj = ResourceManager.GetObject("nether_portal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherite {
            get {
                object obj = ResourceManager.GetObject("netherite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherrack {
            get {
                object obj = ResourceManager.GetObject("netherrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oak_leaves {
            get {
                object obj = ResourceManager.GetObject("oak_leaves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oak_log {
            get {
                object obj = ResourceManager.GetObject("oak_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oak_planks {
            get {
                object obj = ResourceManager.GetObject("oak_planks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obsidian {
            get {
                object obj = ResourceManager.GetObject("obsidian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap portal {
            get {
                object obj = ResourceManager.GetObject("portal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quartz_ore {
            get {
                object obj = ResourceManager.GetObject("quartz_ore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sand {
            get {
                object obj = ResourceManager.GetObject("sand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snowball {
            get {
                object obj = ResourceManager.GetObject("snowball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stone {
            get {
                object obj = ResourceManager.GetObject("stone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stonebrick {
            get {
                object obj = ResourceManager.GetObject("stonebrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap titleBackground {
            get {
                object obj = ResourceManager.GetObject("titleBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap water {
            get {
                object obj = ResourceManager.GetObject("water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xpBarEmpty {
            get {
                object obj = ResourceManager.GetObject("xpBarEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xpBarFull {
            get {
                object obj = ResourceManager.GetObject("xpBarFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
